
# This file is auto-generated by script/generate_homebrew_formula.py
# DO NOT EDIT MANUALLY

class Wrench < Formula
  desc "An educational project designed to explore different types of processor architectures."
  homepage "https://github.com/scobca/wrench"
  url "https://github.com/scobca/wrench/archive/refs/tags/0.0.4.7.15.tar.gz"
  sha256 "dd84e415add846309c21f5c20e48431da7b1767f1a8e8a3539c5305c80207696"
  license "BSD-3-Clause"

  bottle do
    root_url "https://github.com/scobca/wrench/releases/download/0.0.4.7.15"
    url "wrench-Linux-ARM64.tar.gz" => :arm64_linux
    sha256 "49475d6fe1929f32ea9667de43ca9d6cb81fd2429875f9eb311979f97b2f4d95" => :arm64_linux
    url "wrench-Linux-X64.tar.gz" => :x86_64_linux
    sha256 "f752f18fc24163d6955e96aea43e1a5f06dc45536b6557dc7c0e6e4e84a152d3" => :x86_64_linux
    url "wrench-macOS-ARM64.tar.gz" => :arm64_ventura
    sha256 "13d06e238fce08f8124f5d11e627f66151cf24458b3959fcc96185b327fa5036" => :arm64_ventura
  end

  depends_on "ghc" => :build
  depends_on "haskell-stack" => :build

  def install
    system "stack", "build", "--copy-bins", "--local-bin-path", "#{buildpath}/bin"
    bin.install Dir["bin/*"]
  end

  test do
    system "#{bin}/wrench", "--version"
  end
end
