
# This file is auto-generated by script/generate_homebrew_formula.py
# DO NOT EDIT MANUALLY

class Wrench < Formula
  desc "An educational project designed to explore different types of processor architectures."
  homepage "https://github.com/scobca/wrench"
  url "https://github.com/scobca/wrench/archive/refs/tags/0.0.4.7.13.tar.gz"
  sha256 "738765d0f3d969d03c4546c4ae36bc37cd11282914102182351f9c53d0a262d1"
  license "BSD-3-Clause"

  bottle do
    root_url "https://github.com/scobca/wrench/releases/download/0.0.4.7.13"
    sha256 "8c221266f4399916d502ff52bc669b2301fd5697d09c4966fe241bd64c238ee1" => :arm64_linux
    sha256 "84305e160382f5789e29a33ff0108b1edcad10203c6d3afac8e09d372122d08b" => :x86_64_linux
    sha256 "0fb3e507dbf60873c3abb15c7c555aa12b9863fe657c0741f7ca7bdb37927737" => :arm64_ventura
  end

  depends_on "ghc" => :build
  depends_on "haskell-stack" => :build

  def install
    system "stack", "build", "--copy-bins", "--local-bin-path", "#{buildpath}/bin"
    bin.install Dir["bin/*"]
  end

  test do
    system "#{bin}/wrench", "--version"
  end
end
