
# This file is auto-generated by script/generate_homebrew_formula.py
# DO NOT EDIT MANUALLY

class Wrench < Formula
  desc "An educational project designed to explore different types of processor architectures."
  homepage "https://github.com/scobca/wrench"
  url "https://github.com/scobca/wrench/archive/refs/tags/0.0.4.7.14.tar.gz"
  sha256 "332416c69d864eac8e373fa2f3d8f4a1dfcc67fac3738d682add24a2ae3f6b6f"
  license "BSD-3-Clause"

  bottle do
    root_url "https://github.com/scobca/wrench/releases/download/0.0.4.7.14"
    sha256 cellar: :any_skip_relocation, arm64_linux: "ae40fd4f013fddf57703b70889a9f1ae51beb481d35304adf2224e7f767a3192"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "68daa451f9b7d8435964cbc982fa36600fcbfc9139a8e3fcafffb09c960f166b"
    sha256 cellar: :any_skip_relocation, arm64_ventura: "64be6298e0903619bbbd9fc7c7873534a14d0becd852394042345f50a285db2c"
  end

  depends_on "ghc" => :build
  depends_on "haskell-stack" => :build

  def install
    system "stack", "build", "--copy-bins", "--local-bin-path", "#{buildpath}/bin"
    bin.install Dir["bin/*"]
  end

  test do
    system "#{bin}/wrench", "--version"
  end
end
